# Generated by Django 4.1.4 on 2022-12-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_datecompleted_todo_completed_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="completed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
